# -*- coding: utf-8 -*-
class Translator:
    def __init__(self, language='ru'):
        self.language = language
        self.translations = {
            'ru': self._russian(),
            'en': self._english()
        }
    
    def _russian(self):
        return {
            # Main window
            'window_title': "IDS Insight - Графический интерфейс к системе обнаружения вторжений Suricata",
            'events_tab': "События",
            'rules_tab': "Управление правилами",
            'management_tab': "Управление Suricata", 
            'settings_tab': "Настройки",
            'about_tab': "О программе",
            
            # Events tab
            'refresh_events': "Обновить события",
            'all_events': "Все события",
            'alerts_only': "Только алерты", 
            'dns_events': "DNS события",
            'tls_events': "TLS события",
            'events_limit': "Событий:",
            'show_all_events': "Все события",
            'auto_refresh': "Автообновление",
            'refresh_now': "Обновить сейчас",
            'last_hour': "Текущий час",
            'start_time': "С:",
            'end_time': "По:",
            'apply_filter': "Применить",
            'clear_filter': "Сбросить",
            'search_events': "Поиск событий...",
            'timestamp': "Время",
            'event_type': "Тип события", 
            'signature': "Сигнатура",
            'source': "Источник",
            'destination': "Назначение",
            'protocol': "Протокол",
            'severity': "Важность",
            'action': "Действие",
            'details': "Детали",
            
            # Rules tab
            'import_rules': "Импорт правил",
            'refresh': "Обновить",
            'apply_changes': "Применить изменения",
            'create_backup': "Создать резервную копию",
            'update_rules': "Обновить правила",
            'manage_sources': "Управление источниками",
            'search_rules': "Поиск правил:",
            'rule_files': "Файлы правил",
            'rule': "Правило",
            'sid': "SID",
            'status': "Статус",
            'enabled': "Включено",
            'disabled': "Отключено",
            
            # Management tab
            'service_name': "Имя службы:",
            'configure_service': "Настроить службу",
            'start_suricata': "Запустить Suricata",
            'stop_suricata': "Остановить Suricata", 
            'restart_suricata': "Перезапустить Suricata",
            'application_log': "Журнал приложения:",
            'time': "Время",
            'level': "Уровень",
            'message': "Сообщение",
            
            # Settings tab
            'load_config': "Загрузить конфиг",
            'save_config': "Сохранить конфиг",
            'validate_config': "Проверить конфиг",
            'apply_config': "Применить конфиг",
            'suricata_path': "Путь к Suricata:",
            'rules_dir': "Каталог правил:",
            'eve_log': "Файл логов (eve.json):",
            'backup_dir': "Каталог резервных копий:",
            'save_settings': "Сохранить настройки",
            
            # About tab
            'author': "Автор",
            'license': "Лицензия",
            
            # Rule dialog
            'rule_dialog_title': "Детали правила",
            'rule_status': "Статус:",
            'rule_active': "Активно",
            'rule_sid': "SID:",
            'rule_message': "Сообщение:",
            'rule_file': "Файл:",
            'rule_action': "Действие:",
            'rule_raw': "Правило:",
            
            # Context menus
            'disable_rule': "Отключить правило",
            'enable_rule': "Включить правило", 
            'change_action': "Изменить действие...",
            'edit_rule': "Редактировать правило",
            'block_source': "Блокировать источник",
            'block_destination': "Блокировать назначение",
            
            # Messages
            'success': "Успех",
            'error': "Ошибка",
            'rule_updated': "Правило успешно обновлено!",
            'update_failed': "Не удалось обновить правило",
            'loading_events': "Загрузка событий...",
            
            # Status messages
            'suricata_running': "Suricata работает",
            'suricata_stopped': "Suricata остановлена",
            'service_not_found': "Служба не найдена",
            
            'unknown': "Неизвестно",
            'blocked': "Блокировка",
            'logging': "Логирование",
            'rejected': "Отклонение",
            'allowed': "Разрешено",
            'enabled': "Включено",
            'disabled': "Отключено",
            'event_details': "Детали события",
            'time': "Время:",
            'event_type': "Тип события:",
            'source': "Источник:",
            'destination': "Назначение:",
            'protocol': "Протокол:",
            'severity': "Важность:",
            'action': "Действие:",
            'main_info': "Основная информация",
            'raw_data': "Сырые данные",
            'copy_raw_data': "Копировать сырые данные",
            'actions': "Действия",
            'close': "Закрыть",
            'block_source': "Блокировать источник:",
            'block_destination': "Блокировать назначение:",
            'dns_query': "Запрос:",
            'dns_response': "Ответ:",
            'tls_sni': "SNI:",
            'tls_issuer': "Издатель:",
            'flow_state': "Состояние:",
            'flow_reason': "Причина:",
            'category': "Категория:",
            'rule_info': "Информация о правиле",
            'rule_file': "Файл:",
            'rule_sid': "SID:",
            'rule_name': "Название:",
            'view_rule': "Просмотреть",
            'disable_rule': "Отключить",
            'config_not_loaded': "Конфигурация не загружена",
            'config_loaded': "Конфигурация загружена", 
            'config_modified': "Конфигурация изменена (не сохранена)",
            'config_valid': "Конфигурация валидна",
            'config_error': "Ошибка в конфигурации",
            'search_config': "Поиск в конфигурации...",
            'main_settings': "Основные настройки",
            'auto_refresh_warning': "Автообновление отключено",
            'auto_refresh_message': "В режиме 'Все события' автообновление отключено для предотвращения задержек.",
            'rule_disabled_success': "Правило отключено",
            'rule_restart_reminder': "Не забудьте перезапустить Suricata для применения изменений.",
            'rule_action_changed': "Действие правила изменено на '{}'",
            'rule_apply_success': "Успех",
            'rule_apply_error': "Ошибка",
            'time_filter': "Фильтр по времени",
            'checking_status': "Проверка...",
            'developer': "Разработчик:",
            'official_website': "Официальный сайт:",
            'version': "Версия: 1.4",
            'license_agreement': "Лицензионное соглашение:",
            'license_load_error': "Ошибка загрузки лицензии: {}",
            'license_file_not_found': "Файл лицензии (LICENSE.txt) не найден в папке приложения",
            'events_loaded_count': "Загружено событий: {}",
            'last_update': "Последнее обновление: {}",
            'error_loading_events': "Ошибка загрузки событий",
            'dns_query': "DNS запрос",
            'dns': "DNS",
            'tls_handshake': "TLS рукопожатие", 
            'tls': "TLS",
            'bittorrent_dht': "BitTorrent DHT",
            'p2p': "P2P",
            'network_flow': "Сетевой поток",
            'flow': "Поток",
            'other': "Другое",
            'unknown': "Неизвестно",
            'logged': "Записано",
            'allow': "Разрешено",
            'suricata_stopped_successfully': "Suricata успешно остановлена",
            'suricata_started_successfully': "Suricata успешно запущена", 
            'suricata_restarted_successfully': "Suricata успешно перезапущена",
            'error_stopping_suricata': "Ошибка остановки Suricata",
            'error_starting_suricata': "Ошибка запуска Suricata",
            'error_restarting_suricata': "Ошибка перезапуска Suricata",
            'ip_blocked': "IP заблокирован",
            'ip_blocked_message': "IP {} заблокирован и Suricata перезапущен",
            'error_adding_rule': "Не удалось добавить правило блокировки для IP {}",
            'warning_restart_failed': "IP {} добавлен в правила, но не удалось перезапустить Suricata",
            'critical_error': "Критическая ошибка",
            'rule_not_found': "Правило не найдено",
            'rule_not_found_message': "Правило с SID {} не найдено в текущих правилах",
            'select_rule_files': "Выберите файлы правил",
            'rules_imported_successfully': "Правила успешно импортированы!",
            'error_importing_rules': "Ошибка импорта правил",
            'rule_changes_applied': "Изменения правил успешно применены!",
            'error_applying_changes': "Ошибка применения изменений",
            'backup_created': "Резервная копия создана",
            'backup_created_message': "Резервная копия правил создана в:\n{}",
            'error_creating_backup': "Ошибка создания резервной копии",
            'sid_not_specified': "SID правила не указан",
            'check_admin_rights': "Проверьте права администратора",
            'failed_disable_rule': "Не удалось отключить правило SID {}",
            'failed_apply_action': "Не удалось применить действие к правилу SID {}",
            'error_blocking_ip': "Ошибка блокировки IP",
            'language_selection_title': "Выбор языка интерфейса",
            'language_selection_message': "Язык системы определен как Русский.\n\nИспользовать Русский язык интерфейса приложения?\n(При выборе 'Нет' будет включен Английский язык, который можно будет изменить в настройках)",
            'yes_button': "Да",
            'no_button': "Нет",
            'service_status': "Статус службы",
            'service': "Служба",
            'not_installed': "не установлена",
            'stopped': "Остановлена", 
            'starting': "Запускается",
            'stopping': "Останавливается",
            'running': "Работает",
            'resuming': "Возобновляется",
            'pausing': "Приостанавливается",
            'paused': "Приостановлена",
            'accepted_commands': "Принимаемые команды",
            'error_service_info': "Ошибка информации о службе",
            'events_tab': "События",
            'settings_tab': "Настройки",
            'auto_refresh_disabled': "Автообновление отключено",
            'auto_refresh_disabled_message': "В режиме 'Все события' автообновление отключено для предотвращения задержек.",
            'confirm_deletion': "Подтверждение удаления",
            'confirm_delete_file': "Вы уверены, что хотите удалить '{}'?",
            'file_deleted_success': "Файл '{}' удален",
            'error_deleting_file': "Ошибка при удалении файла",
            'rules_enabled': "Все правила в '{}' включены",
            'rules_disabled': "Все правила в '{}' отключены",
            'error_toggling_rules': "Не удалось {} правила в '{}'",
            'no_sources': "Нет источников для обновления",
            'confirm_update': "Подтверждение обновления",
            'confirm_update_message': "Внимание! При обновлении правил все локальные изменения (отключенные правила,\nизмененные действия) будут сброшены. Вы уверены, что хотите продолжить?",
            'update_canceled': "Обновление отменено",
            'update_completed': "Обновление завершено",
            'update_summary': "Успешно обработано источников: {}\nОшибок: {}\nОбновлено файлов: {}\nДобавлено в конфиг: {}",
            'no_changes': "Нет изменений в правилах — файлы не обновлялись.",
            'add_source': "Добавить источник",
            'source_name': "Название:",
            'source_url': "URL:",
            'manage_sources': "Управление источниками правил",
            'add': "Добавить",
            'remove': "Удалить",
            'close': "Закрыть",
            'enable_all_rules': "Включить все правила",
            'disable_all_rules': "Отключить все правила",
            'delete_rule_file': "Удалить файл правил",
            'change_rule_action': "Изменение действия правила",
            'select_action': "Выберите действие для правила SID {}:",
            'rule_action_changed': "Действие правила успешно изменено!",
            'error_changing_action': "Не удалось изменить действие правила",
            'rule_status_changed': "Статус правила успешно изменен!",
            'error_changing_status': "Не удалось изменить статус правила",
            'error_invalid_paths': "Ошибка",
            'settings_saved': "Настройки успешно сохранены!",
            'config_valid': "Конфигурация валидна!",
            'save_config_before_apply': "Сохранение конфигурации",
            'save_config_message': "Конфигурация была изменена. Сохранить перед применением?",
            'suricata_restarted': "Suricata успешно перезапущена с новой конфигурацией!",
            'error_restarting': "Ошибка перезапуска Suricata",
            'error_loading_config': "Ошибка загрузки конфигурации",
            'config_not_modified': "Конфигурация не изменена",
            'config_saved': "Конфигурация успешно сохранена!",
            'error_saving_config': "Ошибка сохранения конфигурации",
            'validation_error': "Ошибка валидации",
            'save_anyway_question': "{}Всё равно сохранить?",
            'service_not_found_title': "Служба не найдена",
            'service_not_found_text': "Служба Suricata '{}' не найдена!",
            'service_not_found_info': "Пожалуйста, настройте правильное имя службы.",
            'missing_rule_files': "Обнаружены отсутствующие файлы правил",
            'missing_files_removed': "Следующие файлы правил отсутствуют и были удалены из конфигурации:",
            'missing_files_not_removed': "Следующие файлы правил отсутствуют:",
            'see_details_below': "Подробности см. ниже.",
            'missing_files_title': "Отсутствуют файлы",
            'missing_files_text': "Следующие файлы не найдены в папке приложения:",
            'error_loading_image': "Ошибка загрузки изображения:\n{}",
            'image_not_found': "Изображение cat.png не найдено",
            'enable': "включить",
            'disable': "отключить",
            'info': "Информация",
            'updating_rules': "Обновление правил...",
            'cancel': "Отмена",
            'update_rules': "Обновление правил", 
            'downloading': "Загрузка",
            'sources_downloaded': "Скачано источников",
            'errors': "Ошибок",
            'copying_files': "Копирование файлов...",
            'updating_config': "Обновление конфигурации...",
            'error_updating_rules': "Ошибка обновления правил",
            'path_not_exists': "Путь не существует",
            'language_changed_restart': "Язык интерфейса изменен. Некоторые изменения вступят в силу после перезапуска приложения.",
            'no_rule_content': "Нет содержимого правила",
            'no_message': "Нет сообщения", 
            'unknown_file': "Неизвестный файл",
            'file_not_in_config': "Файл не в конфигурации",
            'file_not_in_config_message': "Файл правил '{}' не включен в конфигурацию Suricata.\nХотите добавить его сейчас?",
            'file_added_success': "Файл '{}' добавлен в конфигурацию.\nНе забудьте перезапустить Suricata для применения изменений.",
            'error_adding_file': "Не удалось добавить файл '{}' в конфигурацию.",
            'action_updated': "Действие правила успешно изменено!",
            'status_updated': "Статус правила обновлен!",
            'rule_updated': "Правило полностью обновлено!",
            'error_updating_rule': "Не удалось обновить правило",
            'error_changing_status': "Не удалось изменить статус правила", 
            'error_changing_action': "Не удалось изменить действие правила",
            'error_applying_changes': "Ошибка применения изменений",
            'service_configuration': "Настройка службы Suricata",
            'enter_service_name': "Введите имя службы",
            'test_service': "Проверить службу",
            'service_exists_running': "Служба существует (ЗАПУЩЕНА)",
            'service_exists_stopped': "Служба существует (ОСТАНОВЛЕНА)",
            'service_error': "Ошибка - {}",
        }
    
    def _english(self):
        return {
            # Main window
            'window_title': "IDS Insight - Graphical interface for Suricata IDS",
            'events_tab': "Events",
            'rules_tab': "Rules Management",
            'management_tab': "Suricata Management",
            'settings_tab': "Settings", 
            'about_tab': "About",
            
            # Events tab
            'refresh_events': "Refresh Events",
            'all_events': "All Events",
            'alerts_only': "Alerts Only",
            'dns_events': "DNS Events",
            'tls_events': "TLS Events",
            'events_limit': "Events:",
            'show_all_events': "All Events",
            'auto_refresh': "Auto Refresh",
            'refresh_now': "Refresh Now",
            'last_hour': "Last Hour",
            'start_time': "From:",
            'end_time': "To:",
            'apply_filter': "Apply",
            'clear_filter': "Clear",
            'search_events': "Search events...",
            'timestamp': "Timestamp",
            'event_type': "Event Type",
            'signature': "Signature", 
            'source': "Source",
            'destination': "Destination",
            'protocol': "Protocol",
            'severity': "Severity",
            'action': "Action",
            'details': "Details",
            
            # Rules tab
            'import_rules': "Import Rules",
            'refresh': "Refresh",
            'apply_changes': "Apply Changes",
            'create_backup': "Create Backup",
            'update_rules': "Update Rules",
            'manage_sources': "Manage Sources",
            'search_rules': "Search rules:",
            'rule_files': "Rule Files",
            'rule': "Rule",
            'sid': "SID",
            'status': "Status",
            'enabled': "Enabled",
            'disabled': "Disabled",
            
            # Management tab
            'service_name': "Service Name:",
            'configure_service': "Configure Service",
            'start_suricata': "Start Suricata",
            'stop_suricata': "Stop Suricata",
            'restart_suricata': "Restart Suricata",
            'application_log': "Application Log:",
            'time': "Time",
            'level': "Level",
            'message': "Message",
            
            # Settings tab
            'load_config': "Load Config",
            'save_config': "Save Config",
            'validate_config': "Validate Config",
            'apply_config': "Apply Config",
            'suricata_path': "Suricata Path:",
            'rules_dir': "Rules Directory:",
            'eve_log': "Eve Log File:",
            'backup_dir': "Backup Directory:",
            'save_settings': "Save Settings",
            
            # About tab
            'author': "Author",
            'license': "License",
            
            # Rule dialog
            'rule_dialog_title': "Rule Details",
            'rule_status': "Status:",
            'rule_active': "Active",
            'rule_sid': "SID:",
            'rule_message': "Message:",
            'rule_file': "File:",
            'rule_action': "Action:",
            'rule_raw': "Rule:",
            
            # Context menus
            'disable_rule': "Disable Rule",
            'enable_rule': "Enable Rule",
            'change_action': "Change Action...",
            'edit_rule': "Edit Rule",
            'block_source': "Block Source",
            'block_destination': "Block Destination",
            
            # Messages
            'success': "Success",
            'error': "Error",
            'rule_updated': "Rule updated successfully!",
            'update_failed': "Failed to update rule",
            'loading_events': "Loading events...",
            
            # Status messages
            'suricata_running': "Suricata is running",
            'suricata_stopped': "Suricata is stopped",
            'service_not_found': "Service not found",
            
            'unknown': "Unknown",
            'blocked': "Blocked",
            'logging': "Logging",
            'rejected': "Rejected",
            'allowed': "Allowed",
            'enabled': "Enabled",
            'disabled': "Disabled",
            'event_details': "Event Details",
            'time': "Time:",
            'event_type': "Event Type:",
            'source': "Source:",
            'destination': "Destination:",
            'protocol': "Protocol:",
            'severity': "Severity:",
            'action': "Action:",
            'main_info': "Main Information",
            'raw_data': "Raw Data",
            'copy_raw_data': "Copy Raw Data",
            'actions': "Actions",
            'close': "Close",
            'block_source': "Block Source:",
            'block_destination': "Block Destination:",
            'dns_query': "Query:",
            'dns_response': "Response:",
            'tls_sni': "SNI:",
            'tls_issuer': "Issuer:",
            'flow_state': "State:",
            'flow_reason': "Reason:",
            'category': "Category:",
            'rule_info': "Rule Information",
            'rule_file': "File:",
            'rule_sid': "SID:",
            'rule_name': "Name:",
            'view_rule': "View",
            'disable_rule': "Disable",
            'config_not_loaded': "Configuration not loaded",
            'config_loaded': "Configuration loaded",
            'config_modified': "Configuration modified (not saved)", 
            'config_valid': "Configuration valid",
            'config_error': "Configuration error",
            'search_config': "Search in configuration...",
            'main_settings': "Main Settings",
            'auto_refresh_warning': "Auto refresh disabled",
            'auto_refresh_message': "In 'All Events' mode, auto refresh is disabled to prevent delays.",
            'rule_disabled_success': "Rule disabled",
            'rule_restart_reminder': "Don't forget to restart Suricata to apply changes.",
            'rule_action_changed': "Rule action changed to '{}'",
            'rule_apply_success': "Success",
            'rule_apply_error': "Error",
            'time_filter': "Time filter",
            'checking_status': "Checking...",
            'developer': "Developer:",
            'official_website': "Official website:",
            'version': "Version: 1.4",
            'license_agreement': "License Agreement:",
            'license_load_error': "Error loading license: {}",
            'license_file_not_found': "License file (LICENSE.txt) not found in application folder",
            'events_loaded_count': "Events loaded: {}",
            'last_update': "Last update: {}",
            'error_loading_events': "Error loading events",
            'dns_query': "DNS Query",
            'dns': "DNS",
            'tls_handshake': "TLS Handshake",
            'tls': 'TLS', 
            'bittorrent_dht': "BitTorrent DHT",
            'p2p': "P2P",
            'network_flow': "Network Flow",
            'flow': "Flow",
            'other': "Other",
            'unknown': "Unknown",
            'logged': "Logged",
            'allow': "Allowed",
            'suricata_stopped_successfully': "Suricata stopped successfully",
            'suricata_started_successfully': "Suricata started successfully",
            'suricata_restarted_successfully': "Suricata restarted successfully", 
            'error_stopping_suricata': "Error stopping Suricata",
            'error_starting_suricata': "Error starting Suricata",
            'error_restarting_suricata': "Error restarting Suricata",
            'ip_blocked': "IP blocked",
            'ip_blocked_message': "IP {} blocked and Suricata restarted",
            'error_adding_rule': "Failed to add block rule for IP {}",
            'warning_restart_failed': "IP {} added to rules, but failed to restart Suricata",
            'critical_error': "Critical error",
            'rule_not_found': "Rule not found",
            'rule_not_found_message': "Rule with SID {} not found in current rules",
            'select_rule_files': "Select rule files",
            'rules_imported_successfully': "Rules imported successfully!",
            'error_importing_rules': "Error importing rules",
            'rule_changes_applied': "Rule changes applied successfully!",
            'error_applying_changes': "Error applying changes",
            'backup_created': "Backup created",
            'backup_created_message': "Rules backup created at:\n{}",
            'error_creating_backup': "Error creating backup",
            'sid_not_specified': "Rule SID not specified",
            'check_admin_rights': "Check administrator rights",
            'failed_disable_rule': "Failed to disable rule SID {}",
            'failed_apply_action': "Failed to apply action to rule SID {}",
            'error_blocking_ip': "Error blocking IP",
            'language_selection_title': "Interface Language Selection",
            'language_selection_message': "System language detected as English.\n\nUse English interface language?\n(If you select 'No', Russian language will be enabled, which can be changed in settings)",
            'yes_button': "Yes",
            'no_button': "No",
            'service_status': "Service Status",
            'service': "Service", 
            'not_installed': "not installed",
            'stopped': "Stopped",
            'starting': "Starting",
            'stopping': "Stopping",
            'running': "Running",
            'resuming': "Resuming",
            'pausing': "Pausing",
            'paused': "Paused",
            'accepted_commands': "Accepted commands",
            'error_service_info': "Error getting service info",
            'events_tab': "Events",
            'settings_tab': "Settings",
            'auto_refresh_disabled': "Auto refresh disabled",
            'auto_refresh_disabled_message': "In 'All Events' mode, auto refresh is disabled to prevent delays.",
            'confirm_deletion': "Confirm deletion",
            'confirm_delete_file': "Are you sure you want to delete '{}'?",
            'file_deleted_success': "File '{}' deleted",
            'error_deleting_file': "Error deleting file",
            'rules_enabled': "All rules in '{}' enabled",
            'rules_disabled': "All rules in '{}' disabled",
            'error_toggling_rules': "Failed to {} rules in '{}'",
            'no_sources': "No sources to update",
            'confirm_update': "Confirm update",
            'confirm_update_message': "Warning! When updating rules, all local changes (disabled rules,\nmodified actions) will be reset. Are you sure you want to continue?",
            'update_canceled': "Update canceled",
            'update_completed': "Update completed",
            'update_summary': "Successfully processed sources: {}\nErrors: {}\nUpdated files: {}\nAdded to config: {}",
            'no_changes': "No changes in rules - files were not updated.",
            'add_source': "Add source",
            'source_name': "Name:",
            'source_url': "URL:",
            'manage_sources': "Manage rule sources",
            'add': "Add",
            'remove': "Remove",
            'close': "Close",
            'enable_all_rules': "Enable all rules",
            'disable_all_rules': "Disable all rules",
            'delete_rule_file': "Delete rule file",
            'change_rule_action': "Change rule action",
            'select_action': "Select action for rule SID {}:",
            'rule_action_changed': "Rule action changed successfully!",
            'error_changing_action': "Failed to change rule action",
            'rule_status_changed': "Rule status changed successfully!",
            'error_changing_status': "Failed to change rule status",
            'error_invalid_paths': "Error",
            'settings_saved': "Settings saved successfully!",
            'config_valid': "Configuration is valid!",
            'save_config_before_apply': "Save configuration",
            'save_config_message': "Configuration has been modified. Save before applying?",
            'suricata_restarted': "Suricata successfully restarted with new configuration!",
            'error_restarting': "Error restarting Suricata",
            'error_loading_config': "Error loading configuration",
            'config_not_modified': "Configuration not modified",
            'config_saved': "Configuration saved successfully!",
            'error_saving_config': "Error saving configuration",
            'validation_error': "Validation error",
            'save_anyway_question': "{}Save anyway?",
            'service_not_found_title': "Service not found",
            'service_not_found_text': "Suricata service '{}' not found!",
            'service_not_found_info': "Please configure the correct service name.",
            'missing_rule_files': "Missing rule files detected",
            'missing_files_removed': "The following rule files are missing and have been removed from configuration:",
            'missing_files_not_removed': "The following rule files are missing:",
            'see_details_below': "See details below.",
            'missing_files_title': "Missing files",
            'missing_files_text': "The following files were not found in the application folder:",
            'error_loading_image': "Error loading image:\n{}",
            'image_not_found': "Image cat.png not found",
            'enable': "enable",
            'disable': "disable",
            'info': "Information",
            'updating_rules': "Updating rules...",
            'cancel': "Cancel", 
            'update_rules': "Updating rules",
            'downloading': "Downloading",
            'sources_downloaded': "Sources downloaded",
            'errors': "Errors",
            'copying_files': "Copying files...",
            'updating_config': "Updating configuration...",
            'error_updating_rules': "Error updating rules",
            'path_not_exists': "Path does not exist",
            'language_changed_restart': "Interface language changed. Some changes will take effect after restarting the application.",
            'no_rule_content': "No rule content",
            'no_message': "No message",
            'unknown_file': "Unknown file", 
            'file_not_in_config': "File not in configuration",
            'file_not_in_config_message': "Rule file '{}' is not included in Suricata configuration.\nDo you want to add it now?",
            'file_added_success': "File '{}' added to configuration.\nDon't forget to restart Suricata to apply changes.",
            'error_adding_file': "Failed to add file '{}' to configuration.",
            'action_updated': "Rule action changed successfully!",
            'status_updated': "Rule status updated!",
            'rule_updated': "Rule completely updated!",
            'error_updating_rule': "Failed to update rule",
            'error_changing_status': "Failed to change rule status",
            'error_changing_action': "Failed to change rule action", 
            'error_applying_changes': "Error applying changes",
            'service_configuration': "Suricata Service Configuration",
            'enter_service_name': "Enter service name",
            'test_service': "Test service",
            'service_exists_running': "Service exists (RUNNING)",
            'service_exists_stopped': "Service exists (STOPPED)",
            'service_error': "Error - {}",
        }
    
    def tr(self, key):
        return self.translations[self.language].get(key, key)
    
    def set_language(self, language):
        if language in self.translations:
            self.language = language